name: region_group_lasso

backbone:
  classifier__C:
    - 0.01
    # - 0.1
    # - 1
    # - 10
    # - 100
  # options: "mean_std", "flatten" "pca", "summary_stats", "percentiles",
  region_representation: flatten
  flatten:
    group_lasso_alpha_grid:
      - 1e-6
      # - 1e-5 
      # - 1e-4
      # - 1e-3
  mean_std:
    group_lasso_alpha_grid:
      - 1e-6
      # - 1e-5
      # - 1e-4
      # - 1e-3
  pca:
    n_components_per_region: 10
    group_lasso_alpha_grid:
      - 1e-6
      - 1e-5
      - 1e-4
      - 1e-3
  summary_stats:
    group_lasso_alpha_grid:
      - 1e-6
      - 1e-5
      - 1e-4
      - 1e-3
  percentiles:
    group_lasso_alpha_grid:
      - 1e-6
      - 1e-5
      - 1e-4
      - 1e-3