name: camcan
data_reading: bids

metric_to_compute: md
scale: 100

big_delta: 0.024
small_delta: 0.007

big_delta_per_bvalue:
  1000: 24
  2000: 30

tissue_type: gray

# CamCAN data will be resampled to fsLR 32k for analysis
surface_space: fslr_32k