# ==============================
# MODEL CONFIGURATION
# ==============================
pretrain_path: /data/parietal/store3/work/ggomezji/projects/diff_benchmark/MedicalNet_pytorch_files2/pretrain/resnet_10.pth

models:
- name: dummy_classifier
  params:
    name: dummy_classifier
    comment: Dummy Classifier. Testing new dataloader
    batch_size: 32