# ==============================
# MODEL CONFIGURATION
# ==============================
pretrain_path: /data/parietal/store3/work/ggomezji/projects/diff_benchmark/MedicalNet_pytorch_files2/pretrain/resnet_10.pth

models:
- name: pca_linear
  params:
    name: pca_linear
    comment: PCA linear regression. Testing new dataloader
    batch_size: 32