
# ==============================
# GENERAL SETTINGS
# ==============================
metric_to_compute: rtop
scale: 1000     # Scale for Schaefer parcellation (options: 100–1000)
big_delta: 0.0431
small_delta: 0.0106
big_delta_wand: 0.024
small_delta_wand: 0.007
random_state: 42
data_preparation:
  region: VisCent_ExStr #null # If we want all regions, set to null
  # - VisCent_ExStr
  # - VisCent_Striate
  type: spheres # embeddings # null # # Set only when working with spheres or embeddings

# ==============================
# LABEL DEFINITIONS
# ==============================
label_dict:
  ctx-lh-insula: 1035
  ctx-rh-insula: 2035
  3rd-ventricle: 14
  4th-ventricle: 15
  left-lateral-ventricle: 4
  right-lateral-ventricle: 43
  5th-ventricle: 72

# ==============================
# DATA CONFIGURATION
# ==============================
# data_paths:
#   hcp_base: /data/parietal/store4/data/HCP
#   hcp_results: /data/parietal/store3/work/ggomezji/benchmark/HCP900
#   # data_path == (hcp_results): /data/parietal/store2/work/ggomezji/HCP900
#   camcan_base: /data/parietal/store3/work/haggarwa/diffusion/diffusion-preprocessing/data/camcan/derivatives
#   camcan_results: /data/parietal/store3/work/ggomezji/benchmark/CamCAN
#   wand_base: /data/parietal/store3/work/haggarwa/diffusion/diffusion-preprocessing/data/WAND-concat
#   wand_results: /data/parietal/store3/work/ggomezji/benchmark/WAND
#   # FUTURE FEATURE: Indicate mask paths
#   # deen_left: /data/parietal/store2/work/ggomezji/projects/graph_dmri/deen_parcellation_left.func.gii
#   # deen_right: /data/parietal/store2/work/ggomezji/projects/graph_dmri/deen_parcellation_right.func.gii
  
#   csv_file: /data/parietal/store2/work/ggomezji/Merged_HCP_Demographics.csv

# ====== FOR JEAN ZAY RUNS ======
data_paths:
  hcp_base: /lustre/fswork/projects/rech/qlr/commun/HCP900 
  hcp_results: /lustre/fswork/projects/rech/qlr/commun/HCP900
  camcan_base: /data/parietal/store3/work/haggarwa/diffusion/diffusion-preprocessing/data/camcan/derivatives
  camcan_results: /data/parietal/store3/work/ggomezji/benchmark/CamCAN
  wand_base: /data/parietal/store3/work/haggarwa/diffusion/diffusion-preprocessing/data/WAND-concat
  wand_results: /data/parietal/store3/work/ggomezji/benchmark/WAND
  # FUTURE FEATURE: Indicate mask paths
  # deen_left: /data/parietal/store2/work/ggomezji/projects/graph_dmri/deen_parcellation_left.func.gii
  # deen_right: /data/parietal/store2/work/ggomezji/projects/graph_dmri/deen_parcellation_right.func.gii
  
  csv_file: /lustre/fswork/projects/rech/qlr/commun/HCP900/Merged_HCP_Demographics.csv

target_columns:
- Gender

# ==============================
# DATA SPLITS
# ==============================

data_partition:
  train_size: 0.8
  val_size: 0.1
  test_size: 0.1
  n_splits: 5

dataloaders:
  num_workers: 0 # If using joblib use 0

# ==============================
# SLURM CONFIGURATION
# ==============================
use_slurm: false
use_joblib: false # If joblib true, use num_workers = 0
n_jobs: 3
results_path: /data/parietal/store3/work/ggomezji/benchmark/HCP900
slurm:
  log_folder: ./slurm_logs
  jean_zay: false # true
  mem_gb: 32
  gpus_per_node: 1
  cpus_per_task: 8
  timeout_min: 600
  partition: parietal,normal-best
