experiment:
  name: 2dcnn_slices
  comment: 2D CNN with 3-slice input. New logger

data:
  batch_size: 32
  num_workers: 5
  input_channels: 3   # number of slices
  image_size: [224, 224]

models:
- name: 2dcnn

  params:
    dataset: hcp
    backbone:
      input_slices: 145
      # architecture: resnet18
      pretrained: true
      # input_channels: 3
      freeze_backbone: true
      trainable_blocks: 1
      head:
        dropout: 0.5
        hidden_dims: [128]
      
    backend:
      backend: torch
      debug: true
      epochs: 1
      lr: 1e-5
      weight_decay: 0.01
      trainer_kwargs:
        max_epochs: 50 # if lightning backend is used
        accelerator: gpu
        devices: 1

      # optim:
      #   optimizer: adamw
      #   lr: 1e-5
      #   weight_decay: 0.01

    data:
      batch_size: 32
      num_workers: 5
      # input_channels: 3   # number of slices
      image_size: [224, 224]
# - name: 2dcnn

#   params:
#     dataset: hcp
#     backbone:
#       input_slices: 145
#       # architecture: resnet18
#       pretrained: true
#       input_channels: 3
#       freeze_backbone: true
#       trainable_blocks: 0
#       head:
#         dropout: 0.5
#         hidden_dims: [256, 128]
      
#     backend:
#       backend: lightning
#       debug: true
#       epochs: 50
#       trainer_kwargs:
#         # epochs: 6 # if torch backend is used
#         max_epochs: 50 # if lightning backend is used
#         accelerator: gpu
#         devices: 1

#       optim:
#         optimizer: adamw
#         lr: 1e-4
#         weight_decay: 1e-4

#     data:
#       batch_size: 32
#       num_workers: 5
#       input_channels: 3   # number of slices
#       image_size: [224, 224]
# - name: 2dcnn

#   params:
#     dataset: hcp
#     backbone:
#       input_slices: 145
#       # architecture: resnet18
#       pretrained: true
#       input_channels: 3
#       freeze_backbone: true
#       trainable_blocks: 0
#       head:
#         dropout: 0
#         hidden_dims: [256]
      
#     backend:
#       backend: lightning
#       debug: true
#       epochs: 50
#       trainer_kwargs:
#         # epochs: 6 # if torch backend is used
#         max_epochs: 50 # if lightning backend is used
#         accelerator: gpu
#         devices: 1

#       optim:
#         optimizer: adamw
#         lr: 1e-4
#         weight_decay: 1e-4

#     data:
#       batch_size: 32
#       num_workers: 5
#       input_channels: 3   # number of slices
#       image_size: [224, 224]
# - name: 2dcnn

#   params:
#     dataset: hcp
#     backbone:
#       input_slices: 145
#       # architecture: resnet18
#       pretrained: true
#       input_channels: 3
#       freeze_backbone: true
#       trainable_blocks: 0
#       head:
#         dropout: 0.3
#         hidden_dims: [128]
      
#     backend:
#       backend: lightning
#       debug: true
#       epochs: 50
#       trainer_kwargs:
#         # epochs: 6 # if torch backend is used
#         max_epochs: 50 # if lightning backend is used
#         accelerator: gpu
#         devices: 1

#       optim:
#         optimizer: adamw
#         lr: 1e-4
#         weight_decay: 1e-4

#     data:
#       batch_size: 32
#       num_workers: 5
#       input_channels: 3   # number of slices
#       image_size: [224, 224]
# - name: 2dcnn

#   params:
#     dataset: hcp
#     backbone:
#       input_slices: 145
#       # architecture: resnet18
#       pretrained: true
#       input_channels: 3
#       freeze_backbone: true
#       trainable_blocks: 0
#       head:
#         dropout: 0.5
#         hidden_dims: [256, 128]
      
#     backend:
#       backend: torch
#       debug: true
#       epochs: 50
#       trainer_kwargs:
#         # epochs: 6 # if torch backend is used
#         max_epochs: 50 # if lightning backend is used
#         accelerator: gpu
#         devices: 1

#       optim:
#         optimizer: adamw
#         lr: 1e-4
#         weight_decay: 1e-4

#     data:
#       batch_size: 32
#       num_workers: 5
#       input_channels: 3   # number of slices
#       image_size: [224, 224]
# - name: 2dcnn

#   params:
#     dataset: hcp
#     backbone:
#       input_slices: 145
#       # architecture: resnet18
#       pretrained: true
#       input_channels: 3
#       freeze_backbone: true
#       trainable_blocks: 0
#       head:
#         dropout: 0
#         hidden_dims: [256]
      
#     backend:
#       backend: torch
#       debug: true
#       epochs: 50
#       trainer_kwargs:
#         # epochs: 6 # if torch backend is used
#         max_epochs: 50 # if lightning backend is used
#         accelerator: gpu
#         devices: 1

#       optim:
#         optimizer: adamw
#         lr: 1e-4
#         weight_decay: 1e-4

#     data:
#       batch_size: 32
#       num_workers: 5
#       input_channels: 3   # number of slices
#       image_size: [224, 224]
# - name: 2dcnn

#   params:
#     dataset: hcp
#     backbone:
#       input_slices: 145
#       # architecture: resnet18
#       pretrained: true
#       input_channels: 3
#       freeze_backbone: true
#       trainable_blocks: 0
#       head:
#         dropout: 0.3
#         hidden_dims: [128]
      
#     backend:
#       backend: torch
#       debug: true
#       epochs: 50
#       trainer_kwargs:
#         # epochs: 6 # if torch backend is used
#         max_epochs: 50 # if lightning backend is used
#         accelerator: gpu
#         devices: 1

#       optim:
#         optimizer: adamw
#         lr: 1e-4
#         weight_decay: 1e-4

#     data:
#       batch_size: 32
#       num_workers: 5
#       input_channels: 3   # number of slices
#       image_size: [224, 224]
