# ==============================
# MODEL CONFIGURATION
# ==============================
pretrain_path: /data/parietal/store3/work/ggomezji/projects/diff_benchmark/MedicalNet_pytorch_files2/pretrain/resnet_10.pth

models:
- name: linear
  params:
    dataset: hcp
    name: linear
    comment: PCA linear regression. Test new parquet func
    backend: 
      backend: sklearn
      num_classes: 1
    data:
      batch_size: 32
    backbone:
      prediction_task: regression
    