
experiment:
  name: medicalnet_depth18
  comment: MedicalNet regression test
  device: cuda

data:
  batch_size: 16
  num_workers: 5
  input_channels: 1
  region_name: VisCent_ExStr

models:
- name: medicalnet
  params:
    dataset: hcp
    backbone:
      depth: 10
      pretrained: true
      pretrain_path: /data/parietal/store3/work/ggomezji/projects/diff_benchmark/MedicalNet_pytorch_files2/pretrain/resnet_10.pth
      num_classes: 2
      input_channels: 1

    head:
      task: classification
      num_classes: 2
      dropout: 0.0
    backend:
      backend: torch
      trainer_kwargs:
        max_epochs: 3
        accelerator: gpu
        devices: 1
        log_every_n_steps: 10

      optim:
        optimizer: adamw
        lr: 1.0e-5
        weight_decay: 1e-3
        scheduler:
          type: onecycle
          max_lr: 3.0e-3
          pct_start: 0.2
    data:
      batch_size: 16
      num_workers: 5
      input_channels: 1
      region_name: VisCent_ExStr
