# ==============================
# MODEL CONFIGURATION
# ==============================
pretrain_path: /data/parietal/store3/work/ggomezji/projects/diff_benchmark/MedicalNet_pytorch_files2/pretrain/resnet_10.pth

models:
- name: dummy_regressor
  params:
    name: dummy_regressor
    comment: Dummy Regressor. Testing new dataloader
    batch_size: 32