models:
- name: dummy_regressor
  params:
    name: dummy_regressor
    comment: Dummy Regressor. New configuration
    data:
      batch_size: 32
    backbone:
      prediction_task: regression
    backend: 
      backend: sklearn
      num_classes: 1
