# ==============================
# MODEL CONFIGURATION
# ==============================
pretrain_path: /data/parietal/store3/work/ggomezji/projects/diff_benchmark/MedicalNet_pytorch_files2/pretrain/resnet_10.pth

models:
- name: 2dcnn_lite
  params:
    name: 2dcnn_lite
    comment: Test changes made in the file
    input_slices: 145
    num_classes: 2
    device: cpu
    pretrained: true
    freeze_backbone: true
    trainable_blocks: 0
    epochs: 2
    batch_size: 32
    dropout: 0.1
    learning_rate: 1.0e-05
    weight_decay: 1.0e-05
