defaults:
  - dataset: hcp
  - model: dinov2
  - pred_head: binary_classification
  - backend: torch
  - data: default
  - target: gender
  - cluster: margaret
  - analysis: default
  - mesh_pipeline: default
  - _self_

random_state: 42
runtime:
  force: false
  learning_curve_exp: false
  run_id: null
  learning_curve_id: null
  experiment_hash: null


choices:
  model: [region_permutation_group_lasso] #[pointnet] [region_pca, region_group_lasso, region_elasticnet]
  # model.backbone.region_encoder.type: [anatomical_relative] #anatomical_relative, none, anatomical
  # model.backbone.region_encoder.include_size: [false]
  # model.backbone.freeze_backbone: [false]
  model.backbone.region_representation: [flatten] #[flatten, mean_std, summary_stats, percentiles, pca]
  model.backbone.permutation_region: [0] #[16, 17, 18, 19, 20] #[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] #null for random region
  dataset: [hcp] #[abide]
  # dataset: [camcan]
  backend: [sklearn]
  # target: [dx_group]
  # target: [age]
  backend.grid_search_n_jobs: [7]
  pred_head: [mesh_classification] #[mesh_regression] #
  random_state: [42]
  dataset.tissue_type: [gray]
  dataset.metric_to_compute: [md] #[md, sh, mk, b0] #[md, sh, mk, b0]
  cluster: [margaret2_cpu]
  cluster.conf.parallel_type: [None]
  cluster.conf.n_jobs: [10]
  data.num_workers: [0]
  # backend.learning_rate: [1e-3]
  # backend.weight_decay: [1e-3]
  # pred_head.head_type: [additive]  # [simple, additive, attention, transformer]
  # pred_head.head.additive.reg_type: [group_lasso]    # or group_elastic_net / none
  # pred_head.head.additive.lambda1: [0.001]
  # pred_head.head.additive.lambda2: [0.0001]
  # data.batch_size: [2]
 
