defaults:
  - dataset: hcp
  - model: dinov2
  - pred_head: binary_classification
  - backend: torch
  - data: default
  - target: gender
  - cluster: jean_zay
  - analysis: default
  - mesh_pipeline: default
  - _self_

random_state: 42
runtime:
  force: false
  learning_curve_exp: false
  run_id: null
  learning_curve_id: null
  experiment_hash: null

 