name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        # cache: poetry

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '2.1.1' # adjust if needed
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: |
        poetry install --with dev
    
    # - name: Black (check only)
    #   run: |
    #     # Check code formatting with Black
    #     poetry run black --check .
    
    # - name: isort (check only)
    #   run: |
    #     # Check import sorting with isort
    #     poetry run isort --check-only .

    # - name: Pylint
    #   run: |
    #     # Run Pylint on the main script
    #     poetry run pylint src/
    ####
    # - name: Run tests with coverage
    #   run: |
    #     poetry run pytest tests --maxfail=1 --disable-warnings --cov=src --cov-report=xml
    ####
    - name: Run selected tests
      run: |
        poetry run pytest \
          tests/test_cache.py \
          tests/test_data_distribution.py \
          tests/test_dimensions.py \